### ISSUE TITLE
error  occurs when registering.

### ISSUE THREAD

**Issue by IamMegatron2025** [realpython/flask-registration#6]
hello, when I register, it shows error:

`OperationalError: (sqlite3.OperationalError) no such table: users [SQL: u'SELECT users.id AS users_id, users.email AS users_email, users.password AS users_password, users.registered_on AS users_registered_on, users.admin AS users_admin, users.confirmed AS users_confirmed, users.confirmed_on AS users_confirmed_on, users.password_reset_token AS users_password_reset_token \nFROM users \nWHERE users.email = ?\n LIMIT ? OFFSET ?'] [parameters: (u'1837900810@qq.com', 1, 0)]`

why it shows this error? 
can you give some advises?

**Comment by IvyGongoogle** [comment]
why I cannot create a `data-dev.sqlite` after I do 

```
python manage.py db init
python manage.py db migrate -m "init migration"
python manage.py db upgrade

```

?

**Comment by mjhea0** [comment]
Looks like the migrations didn't run. https://github.com/realpython/flask-registration#create-db

**Comment by IamMegatron2025** [comment]
@mjhea0 Thank you. you are right
